Meghesh Shenoy
anmolgkv/letsuseGit pull request #1
Opened 2022-03-28 08:05 UTC by megheshshenoy3

I had finished the task.
For Environment variables I have used Github secrets.

mailid: megheshshenoy3@gmail.com

my repo link - https://github.com/megheshshenoy3/letsuseGit

2022-03-29 16:42 UTC, anmolgkv requested changes
@megheshshenoy3 overall a good implementation,

I have suggested a few changes, please address them and then I will merge them.

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/main.yml
> +
file name should match the action it's performing, like `validatePullRequest.yml`
What do you think?

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/main.yml
> +    container : salesforce/salesforcedx:latest-full
Do you really need the full tag of this docker image?

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/main.yml
> +        - uses: actions/checkout@v2
I would separate each task into separate steps, something like this:

```
steps:
- name: Checkout
  uses: actions/checkout@v2
- name: Authorise Dev Hub
  run: |
      echo $DEV_HUB_URLlocal > devHubURLFile
      sfdx force:auth:sfdxurl:store -d -f devHubURLFile
      rm devHubURLFile
- name: trigger build
  run: |
    chmod +x ./scripts/createScratchOrg.sh
    ./scripts/createScratchOrg.sh -p
```

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/pushtags.yml
> +
Same suggestion, file name should match the action its performing

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/pushtags.yml
> +name: createPackage
Please change the name to `Create Package Version`

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/main.yml
> +      run:
For Ubuntu, the default shell is `bash` and fall back to `sh`, so no need to mention line 27-29

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/pushtags.yml
> +        run:
same here, no need to mention `bash` as the default shell

2022-03-29 16:42 UTC, anmolgkv commented on .github/workflows/pushtags.yml
> +              echo $DEV_HUB_URL > devHubURLFile
same as above, you should break it into multiple named steps

2022-03-29 16:51 UTC, anmolgkv commented on .github/workflows/main.yml
> +              chmod +x ./scripts/CreateScratchOrg.sh
Also, an important part is missing, after everything is completed you need to delete the scratch org so that you don't reach the active scratch org limit.

Hint: send an additional flag to createScratchOrg.sh script when running it from pipeline and in the script file if that flag is passed delete the scratch org at the end

2022-03-29 18:56 UTC, megheshshenoy3 commented on .github/workflows/main.yml
> +        - uses: actions/checkout@v2
I have made the changes.

2022-03-29 18:57 UTC, megheshshenoy3 commented on .github/workflows/pushtags.yml
> +
changed the file name.

2022-03-29 18:57 UTC, megheshshenoy3 commented on .github/workflows/main.yml
> +      run:
I have done the suggested changes.

2022-03-29 18:57 UTC, megheshshenoy3 commented on .github/workflows/pushtags.yml
> +        run:
I have done the suggested changes.

2022-03-29 18:58 UTC, megheshshenoy3 commented on scripts/CreateScratchOrg.sh
> +echo "1 in sh file"
I have removed the echo statements used for debugging.

2022-03-29 18:58 UTC, megheshshenoy3 commented on .github/workflows/main.yml
> +              chmod +x ./scripts/CreateScratchOrg.sh
I have made the necessary changes.

2022-03-29 19:11 UTC, megheshshenoy3 commented on .github/workflows/main.yml
> +    container : salesforce/salesforcedx:latest-full
Not really I have rectified and made the changes.

2022-03-29 19:22 UTC, megheshshenoy3 commented
Hi Anmol,

Thankyou for your inputs.
I have implemented all the changes as suggested by you.

Thanks,
Meghesh

2022-03-30 04:16 UTC, anmolgkv approved these changes

2022-03-30 04:17 UTC, merged